### ISSUE TITLE
Handle missing features in Issues

### ISSUE THREAD

**Issue by Alpha-Guy** [mktcode/octobay#32]
There's a chance, that an issue from a repo with no default langauge, or other default parametrs might be added to the Pinboard. This might happen in case the issue is part of a brand new repo, which has no code added yet. 
The UI fails to display such issues on the Pinboard, as it can't handle missing features for issues. Note: This might extend to PRs and any other features related to repos, in the claim tab.

**Comment by mktcode** [comment]
The issue with the `primaryLanguage` missing is handled. Closing this issue in favour of https://github.com/mktcode/octobay/issues/42.
