### ISSUE TITLE
Find better approach for claimReleasedIssueDeposits

### ISSUE THREAD

**Issue by mktcode** [mktcode/octobay#5]
Currently too many deposits on a single issue would freeze the deposits. Maybe just release 10 deposits at a time or something like that.
https://github.com/mktcode/octobay-contracts/blob/master/contracts/OctoBay.sol#L207

**Comment by Raneet10** [comment]
Maybe have a mapping that stores total deposit for an issue and transfer the amount to the GitHub account's Eth address. Hope I'm not missing anything with the approach. If you approve this, I'll try to implement this at my end.

**Comment by mktcode** [comment]
Well the individual deposits just need to be invalidated so that they can't be withdrawn multiple times. The other option would be to invalidate the whole issue but that would mean that once deposits are withdrawn, the issue cant be used with octobay anymore.... but now that I actually think about it... that doesn't make much sense anyway. Soooo.... I think that would solve the whole issue and your idea is totally fine.

Currently I actually "re-enable" the issue after deposits are withdrawn: https://github.com/mktcode/octobay-contracts/blob/master/contracts/OctoBay.sol#L217
I think that just makes things complicated.

**Comment by mktcode** [comment]
fixed: https://github.com/mktcode/octobay/commit/411254c05f4ff9f0654eb9684daf194ae2cb26bb
